#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ "$OSTYPE" == darwin* ]]; then
  if [[ -e /Users/tsaeger/.nix-profile/bin/vim ]] ; then
      export EDITOR='/Users/tsaeger/.nix-profile/bin/vim'
      export VISUAL='/Users/tsaeger/.nix-profile/bin/vim'
  else
    which nvim > /dev/null
    if [[ $? -eq 0 ]]; then
      export EDITOR='nvim'
      export VISUAL='nvim'
    fi
  fi
else
  export EDITOR='vim'
  export VISUAL='vim'
fi
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/.nix-profile/{bin,sbin}
  ~/.local/bin
  /usr/local/{bin,sbin}
  $path
)

# Python
# from:
# brew install pyenv-virtualenvwrapper
#if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Golang
# export $(go env | grep GOROOT | sed s'/"//g')
# export GOPATH=$HOME/Documents/Development/go

# path=(
#   $path
#   $GOROOT/bin
#   $GOPATH/bin
# )

export CURL_CA_BUNDLE=$HOME/.nix-profile/etc/ssl/certs/ca-bundle.crt

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
